name: RUN UNIT TESTS

on:
    pull_request:
        branches:
            - master
            - dev

jobs:
    jest-unit-test:
    # from https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-node@v3
            with:
              node-version: 16.x
          - run: npm install
          - run: npm run build --if-present
          - run: npm test
